apiVersion: v1
kind: Namespace
metadata:
  name: perses
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perses
  namespace: perses
spec:
  replicas: 1
  selector:
    matchLabels: { app: perses }
  template:
    metadata:
      labels: { app: perses }
    spec:
      containers:
        - name: perses
          image: persesdev/perses:v0.51.1
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /var/lib/perses
          # Updated probes to use /api/v1/health
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: perses
  namespace: perses
spec:
  selector: { app: perses }
  ports:
    - name: http
      port: 8080
      targetPort: http
